export interface ScamCategory {
  id: number;
  name: string;
  sector: string;
  subcategories: string[];
  keywords: string[];
  redFlags: string[];
  minimumTriggerScore: number;
}

export interface VulnerabilityFactor {
  id: number;
  name: string;
  description: string;
  multiplier: number;
  triggerPatterns: string[];
}

export const SECTORS = [
  "government",
  "financial",
  "healthcare",
  "technology",
  "retail",
  "relationship",
  "insurance",
  "real_estate",
  "employment",
  "education",
  "utility",
  "miscellaneous",
] as const;

export const SCAM_CATEGORIES: ScamCategory[] = [
  {
    id: 1,
    name: "IRS Scams",
    sector: "government",
    subcategories: ["tax refund scams", "tax debt scams", "tax resolution scams", "tax identity theft scams", "tax filing fee scams"],
    keywords: [
      "irs", "internal revenue service", "tax refund", "tax debt", "tax resolution",
      "installment agreement", "tax filing", "tax id", "tax fraud", "back taxes",
      "unpaid taxes", "tax audit", "tax lien", "wage garnishment", "tax settlement",
      "tax return", "tax notice", "tax payment", "1099", "w-2",
    ],
    redFlags: [
      "threat of arrest for tax debt",
      "offer to settle for fraction of balance",
      "demand for immediate payment",
      "request for ssn or personal information",
      "caller id spoofing irs number",
      "mention of tax resolution program",
      "reference to installment agreement",
      "threat of wage garnishment",
    ],
    minimumTriggerScore: 60,
  },
  {
    id: 2,
    name: "Social Security (SSA) Scams",
    sector: "government",
    subcategories: ["benefit suspension scams", "ssn misuse scams", "benefit increase scams", "representative payee scams", "ssi scams"],
    keywords: [
      "social security", "ssn", "social security number", "benefits suspended",
      "benefits terminated", "benefit verification", "account flagged",
      "account compromised", "representative payee", "ssi",
      "supplemental security income", "benefit increase", "benefit review",
      "ssa", "social security administration", "social security card",
    ],
    redFlags: [
      "threat of benefit suspension or termination",
      "request for ssn to verify account",
      "claim account is flagged or compromised",
      "offer to increase benefits",
      "unsolicited contact about benefits",
      "threat of legal action",
      "request for personal information",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 3,
    name: "Medicare/CMS Scams",
    sector: "government",
    subcategories: ["medicare card replacement", "medicare coverage", "medicare advantage", "prescription drug plan", "medicare billing", "durable medical equipment"],
    keywords: [
      "medicare", "medicare card", "medicare advantage", "prescription drug plan",
      "medicare coverage", "medicare benefits", "durable medical equipment", "dme",
      "medical equipment", "free medical device", "wheelchair", "oxygen", "cpap",
      "medicare number", "medicare verification", "cms", "medicare supplement",
      "medigap", "part d", "part b",
    ],
    redFlags: [
      "unsolicited offer for new medicare card",
      "claim of new coverage or benefits",
      "offer of free medical equipment",
      "request for medicare number",
      "claim of plan changes",
      "offer of prescription drug discounts",
      "request for payment for verification",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 4,
    name: "FBI Scams",
    sector: "government",
    subcategories: ["money laundering investigation", "fraud investigation", "criminal investigation", "warrant scams", "asset seizure"],
    keywords: [
      "fbi", "federal investigation", "federal charges", "money laundering",
      "fraud investigation", "criminal investigation", "federal crime",
      "federal prosecution", "asset seizure", "federal warrant", "federal agent",
      "federal bureau", "special agent",
    ],
    redFlags: [
      "claim of fbi investigation",
      "threat of federal charges",
      "threat of asset seizure",
      "demand for immediate payment",
      "threat of arrest",
      "caller id spoofing fbi number",
      "reference to specific federal crimes",
    ],
    minimumTriggerScore: 65,
  },
  {
    id: 5,
    name: "DHS/Immigration Scams",
    sector: "government",
    subcategories: ["deportation threat", "immigration status", "visa scams", "green card scams", "ice scams"],
    keywords: [
      "dhs", "ice", "immigration", "deportation", "visa", "green card",
      "immigration status", "immigration enforcement", "immigration violation",
      "undocumented", "visa fraud", "immigration fraud",
      "department of homeland security", "customs enforcement",
    ],
    redFlags: [
      "threat of deportation",
      "threat of immigration enforcement action",
      "claim of immigration status problem",
      "demand for immediate payment",
      "threat of family separation",
      "request for personal information",
      "caller id spoofing dhs or ice number",
    ],
    minimumTriggerScore: 65,
  },
  {
    id: 6,
    name: "FTC Scams",
    sector: "government",
    subcategories: ["identity theft impersonation", "fraud investigation", "consumer protection", "recovery scams"],
    keywords: [
      "ftc", "federal trade commission", "identity theft", "fraud investigation",
      "consumer protection", "identity protection", "identity recovery",
      "fraud recovery", "ftc investigation",
    ],
    redFlags: [
      "impersonation of ftc",
      "claim of identity theft investigation",
      "offer to protect money",
      "request to move money",
      "demand for payment",
      "offer of recovery services",
    ],
    minimumTriggerScore: 60,
  },
  {
    id: 7,
    name: "Court/Legal System Scams",
    sector: "government",
    subcategories: ["traffic violation", "toll violation", "criminal charge", "arrest warrant", "contempt of court", "civil lawsuit", "jury duty"],
    keywords: [
      "court", "judge", "case number", "hearing", "trial", "verdict", "judgment",
      "warrant", "arrest warrant", "bench warrant", "criminal charges", "civil lawsuit",
      "jury duty", "jury summons", "traffic violation", "toll violation",
      "contempt of court", "default judgment", "qr code", "subpoena",
      "court order", "docket", "court clerk",
      "notice of hearing", "failure to appear", "collections agency",
      "enforcement action", "unpaid balance", "settle", "violation fee",
      "scan the qr code", "municipal court", "county court",
      "additional fines", "court costs", "pay the fine",
    ],
    redFlags: [
      "case number with judge name",
      "hearing date and court address",
      "failure to appear warning",
      "default judgment threat",
      "qr code to settle or pay",
      "collections agency referral",
      "fine or fee payment demand",
      "legal citation or authority code",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 8,
    name: "Police/Law Enforcement Scams",
    sector: "government",
    subcategories: ["police impersonation", "sheriff scams", "police bail", "police fine", "police warrant"],
    keywords: [
      "police", "sheriff", "law enforcement", "police investigation",
      "police warrant", "police fine", "bail", "police arrest", "police custody",
      "police department", "sheriff's office", "detective", "officer",
      "badge number", "police report",
    ],
    redFlags: [
      "claim of police investigation",
      "threat of arrest",
      "demand for bail money",
      "demand for fine payment",
      "caller id spoofing police number",
      "threat of immediate police action",
    ],
    minimumTriggerScore: 65,
  },
  {
    id: 9,
    name: "Utility/Government Services Scams",
    sector: "government",
    subcategories: ["electric company", "water/gas company", "telephone company", "government agency", "license/registration"],
    keywords: [
      "utility", "electric", "gas", "water", "telephone", "service disconnection",
      "overdue bill", "account suspension", "utility payment", "utility fraud",
      "power company", "electric bill", "gas bill", "water bill",
    ],
    redFlags: [
      "threat of service disconnection",
      "demand for immediate payment",
      "caller id spoofing utility number",
      "request for personal information",
      "threat of legal action",
      "claim of overdue bill",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 10,
    name: "Veterans Administration (VA) Scams",
    sector: "government",
    subcategories: ["va benefit", "va loan", "va healthcare", "military pension", "military disability"],
    keywords: [
      "va", "veterans administration", "va benefits", "va loan", "va healthcare",
      "military pension", "military disability", "veteran benefits",
      "military service", "discharge papers", "dd-214", "veteran",
    ],
    redFlags: [
      "claim of va benefit eligibility",
      "offer of va loan",
      "claim of va healthcare coverage",
      "request for personal military information",
      "demand for upfront fees",
      "claim of benefit increase",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 11,
    name: "Government Impersonation Scams",
    sector: "government",
    subcategories: ["generic government agency", "government official impersonation", "government employee impersonation", "government contractor"],
    keywords: [
      "government", "federal", "official", "agency", "government official",
      "government employee", "government contractor", "government authority",
      "government investigation", "federal agency", "government notice",
    ],
    redFlags: [
      "vague government agency reference",
      "claim of government authority",
      "threat of legal action",
      "demand for payment",
      "request for personal information",
      "caller id spoofing government number",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 12,
    name: "Public Benefits Scams",
    sector: "government",
    subcategories: ["snap/food stamps", "medicaid", "housing assistance", "liheap", "unemployment benefits"],
    keywords: [
      "snap", "food stamps", "medicaid", "housing assistance", "liheap",
      "unemployment benefits", "public benefits", "welfare", "government assistance",
      "benefit eligibility", "ebt", "food assistance", "section 8",
    ],
    redFlags: [
      "claim of benefit eligibility",
      "offer of benefit increase",
      "request for personal information",
      "demand for upfront fees",
      "claim of benefit verification needed",
      "threat of benefit loss",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 13,
    name: "Bank Impersonation Scams",
    sector: "financial",
    subcategories: ["account compromise", "suspicious activity", "account verification", "account upgrade", "bank security alert"],
    keywords: [
      "bank", "account", "suspicious activity", "account compromise",
      "account verification", "account freeze", "account security",
      "banking information", "account number", "routing number", "account holder",
      "bank account", "checking account", "savings account", "bank alert",
      "bank notice", "bank security",
    ],
    redFlags: [
      "claim of account compromise",
      "suspicious activity alert",
      "request for account verification",
      "request for password or pin",
      "threat of account freeze",
      "request for personal banking information",
      "caller id spoofing bank number",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 14,
    name: "Credit Card Scams",
    sector: "financial",
    subcategories: ["fraud alert", "unauthorized transaction", "credit card activation", "credit limit increase", "credit card replacement"],
    keywords: [
      "credit card", "fraud alert", "unauthorized transaction", "cvv", "card number",
      "credit limit", "card activation", "card replacement", "fraud protection",
      "card security", "visa", "mastercard", "american express", "discover",
      "credit card fraud", "card declined",
    ],
    redFlags: [
      "claim of unauthorized transactions",
      "fraud alert notification",
      "request for card number or cvv",
      "threat of account closure",
      "offer of credit limit increase",
      "claim of card replacement needed",
    ],
    minimumTriggerScore: 48,
  },
  {
    id: 15,
    name: "Mortgage/Loan Scams",
    sector: "financial",
    subcategories: ["mortgage refinancing", "loan modification", "home equity loan", "foreclosure rescue", "loan origination"],
    keywords: [
      "mortgage", "refinancing", "loan modification", "home equity", "foreclosure",
      "foreclosure rescue", "loan origination", "mortgage payment", "refinance",
      "home loan", "upfront fee", "interest rate", "loan officer",
      "mortgage company", "loan approval",
    ],
    redFlags: [
      "unsolicited refinancing offer",
      "unrealistic savings claims",
      "upfront fee demand",
      "threat of foreclosure",
      "offer of loan modification",
      "request for personal financial information",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 16,
    name: "Debt Collection Scams",
    sector: "financial",
    subcategories: ["fake debt collection", "debt settlement", "debt relief", "debt consolidation", "debt validation"],
    keywords: [
      "debt", "debt collection", "debt settlement", "debt relief",
      "debt consolidation", "outstanding debt", "wage garnishment", "asset seizure",
      "lawsuit", "collection agency", "debt validator", "overdue balance",
      "past due", "collections", "debt collector",
    ],
    redFlags: [
      "claim of outstanding debt",
      "threat of lawsuit",
      "threat of wage garnishment",
      "threat of asset seizure",
      "demand for immediate payment",
      "threat of arrest",
      "demand for payment via non-standard method",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 17,
    name: "Investment Scams",
    sector: "financial",
    subcategories: ["ponzi scheme", "pump-and-dump", "penny stock", "cryptocurrency investment", "forex trading", "options trading", "unrealistic return"],
    keywords: [
      "investment", "stock", "cryptocurrency", "bitcoin", "forex", "trading",
      "penny stock", "pump and dump", "ponzi", "unrealistic returns",
      "guaranteed returns", "investment opportunity", "limited time offer",
      "roi", "return on investment", "double your money", "risk-free",
      "passive income", "financial freedom",
    ],
    redFlags: [
      "promise of unrealistic returns",
      "guarantee of profits",
      "pressure to invest quickly",
      "unsolicited investment opportunity",
      "request for upfront payment",
      "claim of limited time opportunity",
      "request for wire transfer or cryptocurrency",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 18,
    name: "Wire Transfer Scams",
    sector: "financial",
    subcategories: ["fake wire transfer requests", "wire transfer verification", "wire transfer reversal", "international wire"],
    keywords: [
      "wire transfer", "wire", "bank transfer", "international transfer",
      "wire verification", "wire reversal", "wire fraud", "wire money",
      "transfer funds", "western union", "moneygram", "swift transfer",
    ],
    redFlags: [
      "request for wire transfer",
      "claim of wire transfer verification needed",
      "request for banking information",
      "claim of wire reversal needed",
      "urgency to wire money",
      "request for wire to unusual destination",
    ],
    minimumTriggerScore: 60,
  },
  {
    id: 19,
    name: "Cryptocurrency Scams",
    sector: "financial",
    subcategories: ["bitcoin investment", "cryptocurrency wallet", "cryptocurrency exchange", "crypto mining", "crypto recovery"],
    keywords: [
      "cryptocurrency", "bitcoin", "ethereum", "wallet", "exchange", "mining",
      "blockchain", "crypto", "digital currency", "private key", "seed phrase",
      "crypto recovery", "bitcoin atm", "nft", "defi", "token",
      "crypto wallet", "coinbase", "binance",
    ],
    redFlags: [
      "promise of cryptocurrency returns",
      "pressure to buy cryptocurrency",
      "request for cryptocurrency payment",
      "claim of crypto wallet compromise",
      "offer of crypto recovery services",
      "request for private keys or seed phrases",
    ],
    minimumTriggerScore: 60,
  },
  {
    id: 20,
    name: "Phishing/Account Takeover Scams",
    sector: "financial",
    subcategories: ["email phishing", "text phishing/smishing", "social media phishing", "account takeover", "password reset"],
    keywords: [
      "phishing", "smishing", "account takeover", "verify account",
      "confirm identity", "suspicious link", "click here", "verify password",
      "account security", "password reset", "login attempt", "unusual sign-in",
      "verify your identity", "confirm your account",
    ],
    redFlags: [
      "suspicious link or attachment",
      "request to click link",
      "request to verify account",
      "claim of account security issue",
      "request for password",
      "suspicious sender address",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 21,
    name: "PayPal/Digital Payment Scams",
    sector: "financial",
    subcategories: ["paypal phishing", "venmo scams", "square cash scams", "apple pay scams", "google pay scams", "fake invoice"],
    keywords: [
      "paypal", "venmo", "square cash", "apple pay", "google pay",
      "digital payment", "payment verification", "account limitation",
      "unauthorized transaction", "zelle", "cash app", "payment app",
      "did not authorize", "invoice", "transaction id",
      "bitcoin", "customer support", "contact our support",
      "call this number", "call us immediately",
    ],
    redFlags: [
      "paypal with phone number to call",
      "claim of unauthorized transaction",
      "bitcoin or crypto purchase invoice",
      "contact support phone number",
      "invoice with no recipient name or address",
      "urgency to call within hours",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 22,
    name: "Check Fraud Scams",
    sector: "financial",
    subcategories: ["fake check", "check overpayment", "cashier's check", "money order"],
    keywords: [
      "check", "cashier's check", "money order", "check overpayment",
      "check fraud", "fake check", "check verification", "wire back",
      "overpayment", "certified check", "bank check",
    ],
    redFlags: [
      "overpayment by check",
      "request to wire back difference",
      "fake check received",
      "claim of check verification needed",
      "request to cash check quickly",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 23,
    name: "Advance Fee Scams",
    sector: "financial",
    subcategories: ["loan advance fee", "credit repair advance fee", "grant advance fee", "inheritance advance fee", "prize claim advance fee"],
    keywords: [
      "advance fee", "processing fee", "upfront fee", "loan advance",
      "credit repair", "grant", "inheritance", "prize claim",
      "guaranteed approval", "guaranteed loan", "administrative fee",
      "handling fee", "registration fee",
    ],
    redFlags: [
      "promise of loan or credit or grant",
      "upfront fee demand",
      "guarantee of approval",
      "request for payment before service",
      "claim of processing fee",
      "request for wire transfer or gift card",
    ],
    minimumTriggerScore: 65,
  },
  {
    id: 24,
    name: "Medicare Scams (Expanded)",
    sector: "healthcare",
    subcategories: ["medicare card replacement", "medicare coverage", "medicare advantage plan", "prescription drug plan", "medicare billing fraud", "medicare supplement"],
    keywords: [
      "medicare", "medicare card", "medicare advantage", "prescription drug plan",
      "medicare coverage", "medicare benefits", "medicare supplement", "medigap",
      "medicare billing", "medicare fraud", "medicare enrollment",
      "part a", "part b", "part d", "medicare number",
    ],
    redFlags: [
      "unsolicited offer for new medicare card",
      "claim of new coverage or benefits",
      "offer of free medical equipment",
      "request for medicare number",
      "claim of plan changes",
      "offer of prescription drug discounts",
      "request for payment for verification",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 25,
    name: "Health Insurance Scams",
    sector: "healthcare",
    subcategories: ["health plan enrollment", "health plan cancellation", "health plan upgrade", "health plan billing", "health plan verification"],
    keywords: [
      "health insurance", "health plan", "coverage", "enrollment",
      "plan cancellation", "plan upgrade", "health plan billing",
      "coverage verification", "premium payment", "open enrollment",
      "marketplace", "obamacare", "affordable care act",
    ],
    redFlags: [
      "unsolicited health plan offer",
      "claim of plan cancellation",
      "request for personal information",
      "demand for payment",
      "claim of plan upgrade",
      "threat of coverage loss",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 26,
    name: "Pharmacy Scams",
    sector: "healthcare",
    subcategories: ["prescription refill", "pharmacy verification", "prescription discount", "pharmacy account", "controlled substance"],
    keywords: [
      "pharmacy", "prescription", "refill", "controlled substance",
      "pharmacy account", "prescription verification", "prescription discount",
      "pharmacy verification", "medication", "drug", "pill", "rx",
      "online pharmacy", "canadian pharmacy",
    ],
    redFlags: [
      "unsolicited prescription offer",
      "request for personal health information",
      "claim of prescription verification needed",
      "offer of prescription discount",
      "request for payment for verification",
      "claim of prescription ready for pickup",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 27,
    name: "Medical Device Scams",
    sector: "healthcare",
    subcategories: ["free medical equipment", "durable medical equipment", "medical device billing", "medical device replacement"],
    keywords: [
      "medical device", "durable medical equipment", "dme", "free equipment",
      "wheelchair", "oxygen", "cpap", "medical equipment", "medicare approved",
      "device replacement", "medical supply", "hearing aid", "back brace",
      "knee brace",
    ],
    redFlags: [
      "offer of free medical equipment",
      "unsolicited medical device offer",
      "claim of medicare approval",
      "request for medicare number",
      "demand for payment for verification",
      "claim of device replacement needed",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 28,
    name: "Doctor/Hospital Scams",
    sector: "healthcare",
    subcategories: ["fake doctor", "fake hospital", "medical bill", "medical procedure", "telemedicine"],
    keywords: [
      "doctor", "hospital", "medical bill", "medical procedure", "telemedicine",
      "medical emergency", "medical verification", "medical office", "physician",
      "clinic", "urgent care", "medical center",
    ],
    redFlags: [
      "unsolicited medical offer",
      "claim of medical emergency",
      "request for payment for verification",
      "suspicious medical bill",
      "claim of medical procedure needed",
      "fake telemedicine link",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 29,
    name: "Dental Scams",
    sector: "healthcare",
    subcategories: ["dental insurance", "dental procedure", "dental billing", "dental discount"],
    keywords: [
      "dental", "dentist", "dental insurance", "dental procedure", "dental billing",
      "dental discount", "dental office", "tooth", "cavity", "root canal",
      "dental plan", "dental coverage",
    ],
    redFlags: [
      "unsolicited dental offer",
      "claim of dental insurance eligibility",
      "demand for upfront payment",
      "claim of dental procedure needed",
      "offer of dental discount",
      "request for personal information",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 30,
    name: "Vision/Eye Care Scams",
    sector: "healthcare",
    subcategories: ["vision insurance", "eye exam", "eyeglass", "contact lens"],
    keywords: [
      "vision", "eye care", "optometrist", "ophthalmologist", "eyeglasses",
      "contact lens", "eye exam", "vision insurance", "vision coverage",
      "glasses", "optical",
    ],
    redFlags: [
      "unsolicited vision insurance offer",
      "claim of eye exam needed",
      "demand for payment",
      "offer of free eyeglasses",
      "request for personal information",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 31,
    name: "Mental Health/Counseling Scams",
    sector: "healthcare",
    subcategories: ["fake therapist", "mental health service", "counseling billing", "telehealth mental health"],
    keywords: [
      "therapist", "counselor", "mental health", "psychology", "counseling",
      "therapy", "telehealth", "mental health service", "psychiatric",
      "psychologist", "behavioral health",
    ],
    redFlags: [
      "unsolicited mental health offer",
      "claim of therapy needed",
      "demand for upfront payment",
      "fake therapist credentials",
      "suspicious telehealth link",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 32,
    name: "Addiction/Recovery Scams",
    sector: "healthcare",
    subcategories: ["fake rehab", "addiction treatment", "recovery program", "substance abuse treatment"],
    keywords: [
      "rehab", "addiction", "recovery", "substance abuse", "treatment",
      "rehabilitation", "addiction treatment", "recovery program", "sobriety",
      "detox", "sober living",
    ],
    redFlags: [
      "unsolicited treatment offer",
      "demand for upfront payment",
      "guarantee of recovery",
      "pressure to enroll immediately",
      "claim of limited spots available",
      "request for personal information",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 33,
    name: "Microsoft/Windows Scams",
    sector: "technology",
    subcategories: ["pop-up security alert", "windows defender", "windows update", "microsoft account", "microsoft support"],
    keywords: [
      "microsoft", "windows", "windows defender", "windows update", "malware",
      "virus", "security alert", "remote access", "system scan", "computer repair",
      "windows error", "blue screen", "bsod", "microsoft support",
      "microsoft technician", "windows license",
    ],
    redFlags: [
      "fake security pop-up",
      "claim of malware infection",
      "request for remote access",
      "demand for payment",
      "threat of data loss",
      "pressure to call number",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 34,
    name: "Apple/iOS Scams",
    sector: "technology",
    subcategories: ["fake apple security alerts", "icloud account", "apple id", "apple support", "iphone/ipad"],
    keywords: [
      "apple", "iphone", "ipad", "icloud", "apple id", "ios", "macos",
      "apple support", "apple security", "device infection", "apple store",
      "itunes", "app store", "apple pay", "facetime",
    ],
    redFlags: [
      "fake security alert",
      "claim of device infection",
      "request for apple id",
      "demand for payment",
      "threat of account lockout",
      "suspicious link",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 35,
    name: "Amazon Scams",
    sector: "technology",
    subcategories: ["amazon account", "amazon phishing", "amazon prime", "amazon seller", "amazon payment"],
    keywords: [
      "amazon", "amazon prime", "amazon account", "amazon seller",
      "amazon payment", "amazon verification", "unauthorized purchase",
      "account compromise", "amazon fraud", "amazon order", "amazon delivery",
      "prime membership",
    ],
    redFlags: [
      "suspicious amazon link",
      "claim of account compromise",
      "request for account verification",
      "claim of unauthorized purchase",
      "threat of account closure",
      "request for payment information",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 36,
    name: "Google Scams",
    sector: "technology",
    subcategories: ["google account", "google play store", "google phishing", "google support", "google payment"],
    keywords: [
      "google", "google account", "google play", "gmail", "google verification",
      "google security", "unauthorized activity", "account suspension",
      "google fraud", "google chrome", "google drive",
    ],
    redFlags: [
      "suspicious google link",
      "claim of account compromise",
      "request for google account verification",
      "claim of unauthorized activity",
      "threat of account suspension",
      "request for payment information",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 37,
    name: "Tech Support Scams",
    sector: "technology",
    subcategories: ["remote access", "computer repair", "software installation", "tech support phone", "tech support email"],
    keywords: [
      "tech support", "computer repair", "remote access", "software",
      "computer problem", "malware", "virus", "system scan", "technical support",
      "computer technician", "teamviewer", "anydesk", "remote desktop",
      "computer virus", "spyware", "trojan",
    ],
    redFlags: [
      "unsolicited tech support offer",
      "claim of computer problem",
      "request for remote access",
      "demand for payment",
      "threat of data loss",
      "pressure to act immediately",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 38,
    name: "Social Media Scams",
    sector: "technology",
    subcategories: ["facebook phishing", "instagram phishing", "twitter phishing", "linkedin phishing", "tiktok phishing"],
    keywords: [
      "facebook", "instagram", "twitter", "linkedin", "tiktok", "social media",
      "account compromise", "account verification", "unusual activity",
      "account suspension", "meta", "snapchat", "youtube",
    ],
    redFlags: [
      "suspicious social media link",
      "claim of account compromise",
      "request for account verification",
      "claim of unusual activity",
      "threat of account suspension",
      "request for password",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 39,
    name: "Email Scams",
    sector: "technology",
    subcategories: ["phishing emails", "spoofed emails", "malicious attachment", "email impersonation", "credential harvesting"],
    keywords: [
      "email", "phishing", "spoofing", "malicious attachment", "suspicious link",
      "verify account", "confirm identity", "email fraud", "email impersonation",
      "spam", "inbox", "email security",
    ],
    redFlags: [
      "suspicious sender address",
      "suspicious link or attachment",
      "request to click link",
      "request to verify account",
      "claim of security issue",
      "urgency to act",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 40,
    name: "Video Call/Zoom Scams",
    sector: "technology",
    subcategories: ["zoom phishing", "video call impersonation", "fake video call", "video conference"],
    keywords: [
      "zoom", "video call", "video conference", "facetime", "skype",
      "video meeting", "screen share", "video phishing", "video impersonation",
      "zoom link", "meeting invite", "webex", "teams meeting",
    ],
    redFlags: [
      "suspicious zoom link",
      "claim of video call needed",
      "request for personal information",
      "suspicious caller on video",
      "claim of security issue",
      "pressure to share screen",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 41,
    name: "Online Shopping Scams",
    sector: "retail",
    subcategories: ["counterfeit product", "non-delivery", "price manipulation", "fake retailer", "online auction"],
    keywords: [
      "online shopping", "counterfeit", "non-delivery", "fake retailer",
      "auction fraud", "product scam", "shipping scam", "delivery scam",
      "online fraud", "fake website", "too good to be true", "sale",
      "discount", "clearance",
    ],
    redFlags: [
      "suspiciously low prices",
      "unsecured website no https",
      "fake retailer website",
      "pressure to buy immediately",
      "request for wire transfer or gift card",
      "no customer reviews",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 42,
    name: "Shipping/Delivery Scams",
    sector: "retail",
    subcategories: ["fake shipping notification", "delivery fee", "package pickup", "customs fee", "international shipping"],
    keywords: [
      "shipping", "delivery", "package", "tracking", "customs", "delivery fee",
      "shipping fee", "package held", "delivery notification", "customs fee",
      "usps", "fedex", "ups", "dhl", "tracking number", "shipment",
    ],
    redFlags: [
      "suspicious shipping notification",
      "claim of delivery fee",
      "request for payment for customs",
      "suspicious tracking link",
      "claim of package held for pickup",
      "request for personal information",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 43,
    name: "Coupon/Discount Scams",
    sector: "retail",
    subcategories: ["fake coupon", "discount code", "cashback", "rebate", "loyalty program"],
    keywords: [
      "coupon", "discount", "discount code", "cashback", "rebate",
      "loyalty program", "promotional code", "special offer", "limited time",
      "exclusive offer", "promo code", "voucher",
    ],
    redFlags: [
      "suspicious coupon code",
      "claim of unrealistic discount",
      "request for personal information",
      "suspicious link",
      "pressure to act quickly",
      "claim of limited time offer",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 44,
    name: "Marketplace Scams",
    sector: "retail",
    subcategories: ["fake seller", "non-payment", "escrow", "overpayment", "buyer protection"],
    keywords: [
      "marketplace", "ebay", "craigslist", "seller", "buyer", "escrow",
      "non-payment", "overpayment", "marketplace fraud", "seller scam",
      "facebook marketplace", "offerup", "letgo",
    ],
    redFlags: [
      "suspicious seller",
      "pressure to use non-standard payment",
      "overpayment request",
      "request for wire transfer",
      "claim of escrow service",
      "pressure to buy quickly",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 45,
    name: "Refund Scams",
    sector: "retail",
    subcategories: ["fake refund", "refund overpayment", "refund reversal", "refund verification"],
    keywords: [
      "refund", "refund scam", "refund overpayment", "refund reversal",
      "refund verification", "refund fraud", "refund notification",
      "overpayment", "money back", "return payment",
    ],
    redFlags: [
      "unsolicited refund offer",
      "claim of refund overpayment",
      "request to wire back difference",
      "fake refund notification",
      "request for personal information",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 46,
    name: "Gift Card Scams",
    sector: "retail",
    subcategories: ["fake gift card", "gift card balance", "gift card resale", "gift card verification"],
    keywords: [
      "gift card", "gift card scam", "gift card code", "gift card verification",
      "gift card balance", "itunes card", "google play card", "amazon card",
      "steam card", "target gift card", "walmart gift card", "prepaid card",
    ],
    redFlags: [
      "pressure to buy gift cards",
      "claim of gift card verification needed",
      "request for gift card codes",
      "suspicious gift card offer",
      "claim of gift card balance issue",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 60,
  },
  {
    id: 47,
    name: "Warranty/Return Scams",
    sector: "retail",
    subcategories: ["fake warranty", "extended warranty", "return fraud", "warranty claim"],
    keywords: [
      "warranty", "extended warranty", "warranty claim", "warranty expiration",
      "return policy", "product warranty", "warranty fraud", "warranty scam",
      "vehicle warranty", "car warranty", "auto warranty",
    ],
    redFlags: [
      "unsolicited warranty offer",
      "claim of warranty expiration",
      "demand for payment for warranty",
      "claim of warranty claim needed",
      "request for personal information",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 48,
    name: "Grandparent Scams",
    sector: "relationship",
    subcategories: ["grandchild in jail", "grandchild in accident", "grandchild in hospital", "grandchild in legal trouble", "grandchild in financial emergency"],
    keywords: [
      "grandchild", "grandparent", "emergency", "crisis", "jail", "hospital",
      "accident", "legal trouble", "financial emergency", "urgent money",
      "don't tell", "grandma", "grandpa", "grandmother", "grandfather",
      "nana", "papa", "bail", "help me", "grandson", "granddaughter",
      "it's me", "please don't tell mom", "please don't tell dad",
      "don't tell mom", "don't tell dad", "keep quiet", "secret",
      "wire money", "send money", "gift card", "western union",
      "i'm in trouble", "i need help", "please help me",
      "don't mention", "lawyer said", "attorney said",
    ],
    redFlags: [
      "emotional plea from grandchild",
      "claim of emergency or crisis",
      "request for money urgently",
      "pressure not to tell family",
      "vague details about situation",
      "request for wire transfer or gift card",
      "caller claims to be grandchild but sounds different",
      "grandchild claims to be in jail or arrested",
      "request to keep situation secret from parents",
      "urgent request combined with secrecy demand",
      "claim of accident with immediate financial need",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 49,
    name: "Romance Scams",
    sector: "relationship",
    subcategories: ["online dating", "military romance", "inheritance romance", "visa/travel romance", "business opportunity romance"],
    keywords: [
      "romance", "online dating", "love", "military", "inheritance", "visa",
      "travel", "business opportunity", "relationship", "sweetheart", "darling",
      "my love", "soulmate", "dating site", "match", "lonely",
      "companionship", "meet in person",
      "miss you", "honey", "my dear", "my dearest", "baby",
      "i love you", "fallen in love", "heart", "forever",
      "financial hardship", "emergency", "business problem",
      "investment opportunity", "wire transfer",
      "keep this private", "don't tell anyone", "our secret",
      "just between us", "nobody needs to know",
      "soldier", "overseas", "deployed", "base", "uniform",
      "oil rig", "engineer abroad", "working overseas",
      "can't video call", "camera broken", "poor connection",
      "send me money", "help me financially", "i need money",
      "western union", "gift card", "bitcoin",
      "we will be together", "i want to meet you",
      "god brought us together", "destiny",
    ],
    redFlags: [
      "online relationship with request for money",
      "claim of love or commitment",
      "story of personal crisis",
      "request for money for travel or visa",
      "promise of future wealth",
      "pressure to keep relationship secret",
      "refusal to meet in person",
      "emotional language combined with financial request",
      "military deployment story with money request",
      "claim of love with isolation pressure",
      "relationship building with urgent financial need",
      "excuses for not video chatting",
      "request for wire transfer or cryptocurrency",
    ],
    minimumTriggerScore: 40,
  },
  {
    id: 50,
    name: "Person-in-Need Scams",
    sector: "relationship",
    subcategories: ["friend in need", "family member in need", "stranger in need", "charity in need"],
    keywords: [
      "need", "emergency", "crisis", "help", "urgent", "money needed",
      "financial help", "assistance needed", "urgent help", "don't tell",
      "stranded", "stuck", "desperate", "please help",
    ],
    redFlags: [
      "unsolicited request for money",
      "emotional story of crisis",
      "pressure to act quickly",
      "request for wire transfer or gift card",
      "pressure not to verify story",
      "vague details about situation",
    ],
    minimumTriggerScore: 60,
  },
  {
    id: 51,
    name: "Catfishing Scams",
    sector: "relationship",
    subcategories: ["fake profile", "fake identity", "fake relationship", "fake social media"],
    keywords: [
      "catfish", "fake profile", "fake identity", "stolen photos",
      "fake relationship", "social media scam", "fake account", "fake person",
      "online friend", "never met",
    ],
    redFlags: [
      "fake social media profile",
      "stolen photos",
      "inconsistent story",
      "refusal to video chat",
      "pressure for relationship commitment",
      "request for money",
    ],
    minimumTriggerScore: 65,
  },
  {
    id: 52,
    name: "Inheritance/Lottery Scams",
    sector: "relationship",
    subcategories: ["fake inheritance", "fake lottery", "fake sweepstakes", "fake prize", "fake settlement"],
    keywords: [
      "inheritance", "lottery", "sweepstakes", "prize", "settlement", "tax",
      "fee", "claim", "eligibility", "unclaimed", "beneficiary", "winner",
      "won", "congratulations", "selected", "chosen",
    ],
    redFlags: [
      "unsolicited inheritance claim",
      "claim of lottery win",
      "claim of prize eligibility",
      "demand for upfront payment",
      "claim of taxes or fees",
      "request for personal information",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 75,
  },
  {
    id: 53,
    name: "Recovery Scams",
    sector: "relationship",
    subcategories: ["fake recovery service", "fake refund", "fake restitution", "fake compensation"],
    keywords: [
      "recovery", "recover", "refund", "restitution", "compensation",
      "recovery service", "recover money", "recovery fee", "previous scam",
      "money back", "get your money back", "scam recovery",
    ],
    redFlags: [
      "unsolicited recovery offer",
      "claim of previous scam recovery",
      "demand for upfront payment",
      "guarantee of recovery",
      "claim of recovery fee",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 70,
  },
  {
    id: 54,
    name: "Charity Scams",
    sector: "relationship",
    subcategories: ["fake charity", "disaster relief", "medical charity", "animal charity", "religious charity"],
    keywords: [
      "charity", "donation", "donate", "relief", "disaster", "medical",
      "animal", "religious", "nonprofit", "tax deductible",
      "charitable contribution", "foundation", "fundraiser", "gofundme",
      "help children", "help veterans", "save lives", "feed the hungry",
      "matching donation", "matching gift", "match your donation",
      "double your impact", "today only", "limited time",
      "your generosity", "make a difference", "give back",
      "100% goes to", "every dollar counts", "sponsor a child",
      "urgent need", "humanitarian crisis", "act of kindness",
      "wire donation", "gift card donation", "cash donation",
    ],
    redFlags: [
      "unsolicited charity request",
      "emotional appeal",
      "pressure to donate",
      "request for wire transfer or gift card",
      "fake charity website",
      "vague use of funds",
      "no charity registration information",
      "matching donation urgency creates false pressure",
      "demand for immediate donation with deadline",
      "charity request via gift card or wire transfer",
      "emotional images combined with urgent financial request",
      "no verifiable charity registration number",
    ],
    minimumTriggerScore: 40,
  },
  {
    id: 55,
    name: "Auto Insurance Scams",
    sector: "insurance",
    subcategories: ["fake auto insurance", "auto insurance rate", "auto insurance claim", "auto insurance cancellation"],
    keywords: [
      "auto insurance", "car insurance", "insurance rate", "insurance claim",
      "insurance cancellation", "insurance policy", "premium", "coverage",
      "vehicle", "auto policy", "liability", "collision",
    ],
    redFlags: [
      "unsolicited insurance offer",
      "claim of rate reduction",
      "demand for upfront payment",
      "request for personal information",
      "claim of policy cancellation",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 56,
    name: "Home Insurance Scams",
    sector: "insurance",
    subcategories: ["fake home insurance", "home insurance rate", "home insurance claim", "home insurance cancellation"],
    keywords: [
      "home insurance", "homeowners insurance", "insurance rate",
      "insurance claim", "insurance cancellation", "insurance policy",
      "premium", "coverage", "property", "homeowner",
    ],
    redFlags: [
      "unsolicited insurance offer",
      "claim of rate reduction",
      "demand for upfront payment",
      "request for personal information",
      "claim of policy cancellation",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 57,
    name: "Life Insurance Scams",
    sector: "insurance",
    subcategories: ["fake life insurance", "life insurance rate", "life insurance claim", "life insurance policy"],
    keywords: [
      "life insurance", "insurance rate", "insurance claim", "insurance policy",
      "premium", "coverage", "beneficiary", "policy", "death benefit",
      "whole life", "term life",
    ],
    redFlags: [
      "unsolicited insurance offer",
      "claim of rate reduction",
      "demand for upfront payment",
      "request for personal information",
      "claim of policy issue",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 58,
    name: "Burial/Funeral Insurance Scams",
    sector: "insurance",
    subcategories: ["fake burial insurance", "fake funeral insurance", "prepaid funeral", "funeral home"],
    keywords: [
      "burial insurance", "funeral insurance", "prepaid funeral", "funeral home",
      "funeral costs", "burial costs", "funeral arrangements", "cremation",
      "final expense", "funeral plan",
    ],
    redFlags: [
      "unsolicited funeral insurance offer",
      "pressure to prepay funeral",
      "demand for upfront payment",
      "claim of limited time offer",
      "request for personal information",
      "vague funeral home information",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 59,
    name: "Travel Insurance Scams",
    sector: "insurance",
    subcategories: ["fake travel insurance", "travel insurance claim", "travel insurance cancellation"],
    keywords: [
      "travel insurance", "travel protection", "trip insurance", "travel claim",
      "insurance cancellation", "travel policy", "coverage", "premium",
      "trip cancellation", "travel guard",
    ],
    redFlags: [
      "unsolicited travel insurance offer",
      "demand for upfront payment",
      "claim of limited time offer",
      "request for personal information",
      "claim of policy cancellation",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 60,
    name: "Real Estate Investment Scams",
    sector: "real_estate",
    subcategories: ["fake real estate investment", "real estate flipping", "rental property", "commercial real estate"],
    keywords: [
      "real estate", "investment", "property", "real estate investment",
      "real estate flipping", "rental property", "commercial property",
      "property investment", "real estate deal", "flip houses",
    ],
    redFlags: [
      "unsolicited investment opportunity",
      "promise of unrealistic returns",
      "pressure to invest quickly",
      "demand for upfront payment",
      "vague property details",
      "request for wire transfer",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 61,
    name: "Rental Scams",
    sector: "real_estate",
    subcategories: ["fake rental listing", "rental overpayment", "rental deposit", "rental verification"],
    keywords: [
      "rental", "apartment", "house", "rental listing", "rental deposit",
      "rental payment", "landlord", "tenant", "rental fraud", "fake listing",
      "security deposit", "first month's rent", "lease",
    ],
    redFlags: [
      "suspiciously low rental price",
      "pressure to pay quickly",
      "request for wire transfer or gift card",
      "fake rental listing",
      "overpayment request",
      "request for personal information",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 62,
    name: "Foreclosure Rescue Scams",
    sector: "real_estate",
    subcategories: ["fake foreclosure rescue", "loan modification", "foreclosure prevention"],
    keywords: [
      "foreclosure", "foreclosure rescue", "loan modification",
      "foreclosure prevention", "foreclosure scam", "mortgage crisis",
      "home loss", "foreclosure help", "save your home",
    ],
    redFlags: [
      "unsolicited foreclosure rescue offer",
      "demand for upfront payment",
      "guarantee of foreclosure prevention",
      "claim of special program",
      "pressure to act quickly",
      "request for personal financial information",
    ],
    minimumTriggerScore: 60,
  },
  {
    id: 63,
    name: "Home Repair Scams",
    sector: "real_estate",
    subcategories: ["fake home repair", "home improvement", "contractor fraud", "home inspection"],
    keywords: [
      "home repair", "home improvement", "contractor", "home inspection",
      "repair estimate", "repair quote", "home maintenance", "home renovation",
      "roofing", "plumbing", "handyman",
    ],
    redFlags: [
      "unsolicited home repair offer",
      "pressure to hire contractor",
      "demand for upfront payment",
      "vague repair description",
      "pressure to act quickly",
      "request for cash payment",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 64,
    name: "Job Offer Scams",
    sector: "employment",
    subcategories: ["fake job offer", "work-from-home", "remote job", "job interview"],
    keywords: [
      "job", "employment", "job offer", "work from home", "remote job",
      "job interview", "salary", "position", "hiring", "employment scam",
      "work at home", "online job", "easy money", "no experience needed",
    ],
    redFlags: [
      "unsolicited job offer",
      "job offer without interview",
      "unrealistic salary offer",
      "demand for upfront payment",
      "pressure to start immediately",
      "request for personal information",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 65,
    name: "Employment Advance Payment Scams",
    sector: "employment",
    subcategories: ["work-from-home advance fee", "job training advance fee", "job placement advance fee"],
    keywords: [
      "advance fee", "training fee", "placement fee", "work from home",
      "job training", "job placement", "guaranteed job", "employment fee",
      "starter kit", "equipment fee",
    ],
    redFlags: [
      "demand for upfront payment",
      "claim of training fee",
      "claim of placement fee",
      "guarantee of job",
      "pressure to pay quickly",
      "request for wire transfer or gift card",
    ],
    minimumTriggerScore: 65,
  },
  {
    id: 66,
    name: "Contractor/Gig Worker Scams",
    sector: "employment",
    subcategories: ["fake contractor", "gig worker payment", "freelancer payment", "independent contractor"],
    keywords: [
      "contractor", "gig worker", "freelancer", "independent contractor",
      "gig economy", "contractor payment", "freelance work", "contractor fraud",
      "side hustle", "contract work",
    ],
    redFlags: [
      "unsolicited contractor opportunity",
      "demand for upfront payment",
      "vague job description",
      "pressure to start immediately",
      "request for personal information",
      "non-standard payment method",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 67,
    name: "Student Loan Scams",
    sector: "education",
    subcategories: ["student loan forgiveness", "student loan consolidation", "student loan repayment", "student loan servicing"],
    keywords: [
      "student loan", "loan forgiveness", "loan consolidation", "loan repayment",
      "student debt", "loan servicing", "federal student loan", "loan scam",
      "student loan relief", "loan discharge",
    ],
    redFlags: [
      "unsolicited loan forgiveness offer",
      "demand for upfront payment",
      "guarantee of loan forgiveness",
      "claim of special program",
      "pressure to act quickly",
      "request for personal financial information",
    ],
    minimumTriggerScore: 60,
  },
  {
    id: 68,
    name: "College Tuition Scams",
    sector: "education",
    subcategories: ["fake college", "tuition payment", "scholarship", "financial aid"],
    keywords: [
      "college", "tuition", "scholarship", "financial aid", "college scam",
      "tuition payment", "financial aid fraud", "scholarship fraud",
      "university", "enrollment",
    ],
    redFlags: [
      "unsolicited scholarship offer",
      "demand for upfront payment",
      "guarantee of scholarship",
      "fake college website",
      "pressure to act quickly",
      "request for personal information",
    ],
    minimumTriggerScore: 55,
  },
  {
    id: 69,
    name: "Online Course Scams",
    sector: "education",
    subcategories: ["fake online course", "course credential", "course refund", "diploma mill"],
    keywords: [
      "online course", "course scam", "fake credential", "diploma mill",
      "course provider", "online learning", "course enrollment", "fake diploma",
      "certification", "accredited",
    ],
    redFlags: [
      "suspiciously low course price",
      "fake course provider",
      "guarantee of credential",
      "pressure to enroll quickly",
      "request for personal information",
      "fake diploma offer",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 70,
    name: "Utility Company Scams",
    sector: "utility",
    subcategories: ["electric company", "gas company", "water company", "internet service provider"],
    keywords: [
      "utility", "electric", "gas", "water", "internet", "service disconnection",
      "overdue bill", "account suspension", "utility payment", "utility fraud",
      "power bill", "electric company", "gas company",
    ],
    redFlags: [
      "threat of service disconnection",
      "demand for immediate payment",
      "caller id spoofing utility number",
      "request for personal information",
      "threat of legal action",
      "claim of overdue bill",
    ],
    minimumTriggerScore: 50,
  },
  {
    id: 71,
    name: "Home Security System Scams",
    sector: "utility",
    subcategories: ["fake security system", "security system monitoring", "security system upgrade", "security system cancellation"],
    keywords: [
      "security system", "home security", "alarm system", "monitoring service",
      "security monitoring", "security upgrade", "home alarm", "security scam",
      "adt", "ring", "simplisafe",
    ],
    redFlags: [
      "unsolicited security system offer",
      "demand for upfront payment",
      "claim of system upgrade needed",
      "pressure to sign contract",
      "request for personal information",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 72,
    name: "Internet Service Provider Scams",
    sector: "utility",
    subcategories: ["fake isp", "internet speed", "internet upgrade", "internet billing"],
    keywords: [
      "internet service provider", "isp", "internet speed", "internet upgrade",
      "internet billing", "internet service", "broadband", "internet scam",
      "fiber", "cable internet", "wifi",
    ],
    redFlags: [
      "unsolicited isp offer",
      "claim of service upgrade",
      "demand for upfront payment",
      "caller id spoofing isp number",
      "request for personal information",
      "pressure to act quickly",
    ],
    minimumTriggerScore: 45,
  },
  {
    id: 73,
    name: "Lottery/Sweepstakes Scams",
    sector: "miscellaneous",
    subcategories: ["fake lottery", "fake sweepstakes", "fake prize", "publishers clearing house"],
    keywords: [
      "lottery", "sweepstakes", "prize", "publishers clearing house", "pch",
      "tax", "fee", "claim", "eligibility", "unclaimed", "prize winner",
      "you have won", "million dollars", "jackpot", "drawing",
    ],
    redFlags: [
      "unsolicited prize claim",
      "demand for upfront payment",
      "claim of taxes or fees",
      "pressure to act quickly",
      "request for personal information",
      "claim of limited time offer",
    ],
    minimumTriggerScore: 75,
  },
  {
    id: 74,
    name: "Funeral/Cemetery Scams",
    sector: "miscellaneous",
    subcategories: ["funeral home", "cemetery plot", "funeral service", "prepaid funeral"],
    keywords: [
      "funeral", "cemetery", "funeral home", "funeral service", "prepaid funeral",
      "burial plot", "cremation", "funeral arrangements", "funeral costs",
      "memorial", "casket", "deceased", "memorial service", "burial",
      "obituary", "death certificate", "remains", "embalming",
      "grave site", "headstone", "urn", "wake", "viewing",
      "prepay", "pre-arrangement", "final expenses",
      "burial insurance", "funeral insurance", "immediate need",
      "outstanding balance", "unpaid funeral", "additional fees",
      "transfer fee", "release fee", "transport fee",
      "death", "condolences", "monument", "flowers",
      "storage fee", "handling fee", "immediate payment",
      "today only", "limited time", "family emergency",
      "loss", "grief", "arrangements needed",
      "plot", "cemetery plot",
    ],
    redFlags: [
      "pressure to prepay funeral",
      "demand for upfront payment",
      "vague funeral home information",
      "claim of limited time offer",
      "request for personal information",
      "high-pressure sales tactics",
      "surprise additional fees after funeral",
      "demand for immediate payment to release remains",
      "wire transfer required for funeral services",
      "fake obituary notice with payment request",
      "unsolicited funeral insurance with urgency",
    ],
    minimumTriggerScore: 35,
  },
  {
    id: 75,
    name: "Pet/Animal Scams",
    sector: "miscellaneous",
    subcategories: ["pet adoption", "pet shipping", "pet breeding", "pet veterinary", "pet insurance"],
    keywords: [
      "pet", "animal", "dog", "cat", "adoption", "breeding", "shipping",
      "veterinary", "pet insurance", "pet scam", "animal scam", "puppy",
      "kitten", "breeder", "pet deposit",
      "rescue", "shelter", "rehome", "rehoming", "free to good home",
      "urgent rehome", "must find home", "leaving country",
      "shipping fee", "transport fee", "vaccination fee", "crate fee",
      "pet shipping", "delivery fee", "health certificate",
      "akc registered", "purebred", "pedigree",
      "deposit required", "non-refundable deposit",
      "available now", "last one", "many inquiries",
      "foster", "breed", "wire transfer", "payment",
      "immediately", "family moving", "overseas", "relocation",
      "new home", "non-refundable", "hold", "secure", "available",
      "deposit", "urgent",
    ],
    redFlags: [
      "unsolicited pet offer",
      "demand for upfront payment",
      "fake pet listing",
      "pressure to act quickly",
      "request for wire transfer or gift card",
      "request for personal information",
      "deposit for pet with urgency to act fast",
      "shipping fee for free pet",
      "pet only available for limited time",
      "multiple additional fees after initial deposit",
      "seller leaving country urgently needs to rehome",
      "cannot meet in person to see the pet",
    ],
    minimumTriggerScore: 35,
  },
];

export const SENIOR_VULNERABILITY_FACTORS: VulnerabilityFactor[] = [
  {
    id: 1,
    name: "Authority Exploitation",
    description: "Exploits seniors' trust in authority figures and institutions",
    multiplier: 1.4,
    triggerPatterns: [
      "irs", "fbi", "police", "government", "federal", "official",
      "social security", "medicare", "department", "agency", "officer",
      "agent", "inspector", "investigator", "commissioner",
      "court", "judge", "clerk of court",
    ],
  },
  {
    id: 2,
    name: "Emotional Manipulation",
    description: "Uses emotional tactics to cloud judgment",
    multiplier: 1.5,
    triggerPatterns: [
      "grandchild", "grandson", "granddaughter", "family emergency",
      "love", "darling", "sweetheart", "miss you", "need your help",
      "crying", "scared", "afraid", "please help", "only you",
      "desperate", "heartbroken", "honey", "my dear", "my dearest",
      "i love you", "fallen in love", "soulmate", "baby",
      "god brought us together", "destiny", "forever",
    ],
  },
  {
    id: 3,
    name: "Urgency Pressure",
    description: "Creates artificial time pressure to prevent careful consideration",
    multiplier: 1.4,
    triggerPatterns: [
      "immediately", "right now", "today only", "last chance", "expires",
      "within 24 hours", "within 48 hours", "act now", "don't delay",
      "time is running out", "limited time", "deadline", "urgent",
      "asap", "hurry",
    ],
  },
  {
    id: 4,
    name: "Vague Claims",
    description: "Uses intentionally vague claims that are hard to verify",
    multiplier: 1.2,
    triggerPatterns: [
      "your account", "your information", "your records", "our records show",
      "we have detected", "it has come to our attention", "a problem with",
      "an issue with", "irregularities", "discrepancies",
    ],
  },
  {
    id: 5,
    name: "Isolation Tactics",
    description: "Tries to prevent seniors from consulting family or friends",
    multiplier: 1.5,
    triggerPatterns: [
      "don't tell anyone", "do not tell", "keep this between us",
      "keep this secret", "confidential matter", "private matter",
      "don't let anyone know", "don't discuss this", "for your eyes only",
      "between you and me",
    ],
  },
  {
    id: 6,
    name: "Tech Unfamiliarity",
    description: "Exploits seniors' potential unfamiliarity with technology",
    multiplier: 1.3,
    triggerPatterns: [
      "remote access", "download this", "install this", "click here",
      "your computer has", "virus detected", "malware found",
      "system compromised", "tech support", "computer infected",
      "firewall", "antivirus expired",
    ],
  },
  {
    id: 7,
    name: "Generosity Appeal",
    description: "Exploits seniors' generosity and desire to help",
    multiplier: 1.3,
    triggerPatterns: [
      "charity", "donation", "help children", "help veterans",
      "disaster relief", "feed the hungry", "save lives",
      "your generosity", "make a difference", "give back",
    ],
  },
  {
    id: 8,
    name: "Financial Security Assumption",
    description: "Targets seniors' assumed financial stability",
    multiplier: 1.3,
    triggerPatterns: [
      "retirement", "pension", "savings", "nest egg", "investment opportunity",
      "guaranteed returns", "double your money", "financial freedom",
      "passive income", "annuity", "401k", "ira",
    ],
  },
  {
    id: 9,
    name: "Politeness Exploitation",
    description: "Takes advantage of seniors' politeness and difficulty saying no",
    multiplier: 1.2,
    triggerPatterns: [
      "just a moment of your time", "i appreciate your patience",
      "thank you for your cooperation", "we value your loyalty",
      "as a valued customer", "we selected you",
    ],
  },
  {
    id: 10,
    name: "Embarrassment Prevention",
    description: "Uses threat of embarrassment to prevent seeking help",
    multiplier: 1.3,
    triggerPatterns: [
      "embarrassing", "adult content", "inappropriate material",
      "illegal activity", "pornographic", "your browsing history",
      "we have recorded you", "we have footage", "compromising",
    ],
  },
  {
    id: 11,
    name: "Trust in Institutions",
    description: "Exploits trust in banks, hospitals, and government",
    multiplier: 1.3,
    triggerPatterns: [
      "bank", "hospital", "doctor", "medicare", "social security",
      "insurance company", "pharmacy", "court", "treasury",
      "department of", "bureau of",
    ],
  },
  {
    id: 12,
    name: "Cognitive Changes",
    description: "Uses complex or confusing language to overwhelm",
    multiplier: 1.2,
    triggerPatterns: [
      "pursuant to", "notwithstanding", "hereinafter", "whereas",
      "in accordance with section", "under penalty of perjury",
      "statutory requirement", "regulatory compliance",
    ],
  },
  {
    id: 13,
    name: "Social Isolation",
    description: "Targets seniors who may be socially isolated",
    multiplier: 1.4,
    triggerPatterns: [
      "lonely", "alone", "companionship", "friend", "someone to talk to",
      "we care about you", "you deserve", "special person",
      "chosen specifically", "selected just for you",
    ],
  },
  {
    id: 16,
    name: "Romance Exploitation",
    description: "Romance scams exploit seniors' loneliness and desire for companionship",
    multiplier: 1.5,
    triggerPatterns: [
      "love", "sweetheart", "darling", "miss you", "honey",
      "my dear", "romance", "dating", "relationship", "soulmate",
      "wire transfer", "send money", "gift card", "help me financially",
      "western union", "bitcoin", "financial hardship", "emergency",
    ],
  },
  {
    id: 14,
    name: "Financial Vulnerability",
    description: "Targets fixed income or financial concerns",
    multiplier: 1.3,
    triggerPatterns: [
      "fixed income", "social security check", "pension check",
      "reverse mortgage", "home equity", "cash out", "low income",
      "financial hardship", "struggling", "debt relief",
    ],
  },
  {
    id: 15,
    name: "Health Concerns",
    description: "Exploits health-related anxieties common in seniors",
    multiplier: 1.3,
    triggerPatterns: [
      "health alert", "medical emergency", "prescription", "medication",
      "doctor says", "test results", "diagnosis", "treatment needed",
      "health insurance", "medicare coverage", "medical device",
      "free medical", "health screening",
    ],
  },
];

export const CROSS_CUTTING_KEYWORDS = {
  urgency: [
    "urgent", "act now", "immediate action", "immediately", "today",
    "right now", "asap", "hurry", "quickly", "fast", "deadline",
    "time-sensitive", "expiring", "expires soon", "limited time",
    "last chance", "do not delay", "verify now", "confirm now",
    "respond immediately", "within 24 hours", "within 48 hours",
    "action required", "time is running out",
    "as soon as possible", "within the next",
  ],
  financial: [
    "payment", "pay", "transfer", "wire", "wire transfer", "account number",
    "credit card", "debit card", "billing", "invoice", "refund", "deposit",
    "withdrawal", "transaction", "gift card", "bitcoin", "cryptocurrency",
    "cash app", "venmo", "zelle", "western union", "money order",
    "send money", "processing fee", "upfront fee", "advance fee",
    "settle your balance", "unpaid balance", "pay the fine",
    "scan the qr code", "qr code to pay", "scan to pay",
    "settle your unpaid", "pay your balance",
  ],
  threats: [
    "suspended", "locked", "compromised", "fraud", "fraudulent",
    "unauthorized", "hacked", "security breach", "virus", "malware",
    "infected", "alert", "warning", "critical alert", "legal action",
    "arrest", "warrant", "penalty", "fine", "prosecution", "jail",
    "prison", "felony", "criminal charges",
    "failure to appear", "default judgment", "collections agency",
    "enforcement action", "unpaid balance", "additional fines",
    "court costs", "may result in", "referral to collections",
    "did not authorize", "unauthorized payment", "unauthorized purchase",
  ],
  personalInfoRequest: [
    "password", "pin", "social security number", "ssn", "account number",
    "credit card number", "card number", "verification code", "confirm identity",
    "verify identity", "click here", "click link", "download", "install",
    "call this number", "call us", "provide your", "share your",
    "send your", "enter your", "update your information",
    "verify your account", "confirm your account", "routing number",
    "date of birth", "mother's maiden name", "security question",
  ],
  impersonation: [
    "on behalf of", "official message", "authorized by", "verified by",
    "from the desk of", "this is a notice from", "we are contacting you",
    "your account with", "as your provider", "security team",
    "fraud department", "security department", "compliance department",
  ],
  giftCardPayment: [
    "gift card", "itunes card", "google play card", "amazon card",
    "steam card", "target gift card", "walmart gift card", "prepaid card",
    "buy gift cards", "gift card codes", "scratch off the back",
    "read me the numbers",
  ],
  secrecy: [
    "don't tell anyone", "do not tell", "keep this secret",
    "don't let anyone know", "keep this between us", "confidential",
    "private matter", "don't discuss this", "for your eyes only",
    "don't tell your family",
  ],
};

export const LEGITIMATE_SENDERS: Record<string, string[]> = {
  banks: ["chase", "bank of america", "wells fargo", "citi", "capital one", "td bank", "us bank", "pnc", "truist", "regions"],
  pharmacies: ["cvs", "walgreens", "walmart pharmacy", "amazon pharmacy", "kroger pharmacy", "rite aid"],
  services: ["amazon", "apple", "microsoft", "google", "paypal", "ebay", "netflix", "spotify", "hulu", "disney+"],
  utilities: ["duke energy", "comed", "verizon", "at&t", "comcast", "xfinity", "spectrum", "t-mobile", "sprint"],
  healthcare: ["medicare", "blue cross", "aetna", "united healthcare", "cigna", "humana", "kaiser permanente"],
};

export const LEGITIMATE_PATTERNS = [
  {
    name: "Informational Notification",
    keywords: ["prescription ready", "package delivered", "appointment confirmed", "order shipped", "payment received", "statement available"],
    scoreReduction: 20,
    description: "Legitimate informational message with no request for action",
  },
  {
    name: "Security Notification",
    keywords: ["detected login", "password changed", "accessed from", "new device", "sign-in from", "security alert", "unusual activity", "new device login", "suspicious activity", "unauthorized access", "confirm login"],
    scoreReduction: 25,
    description: "Legitimate security notification without request for personal info",
  },
  {
    name: "Service Notification",
    keywords: ["bill of", "order confirmed", "appointment scheduled", "delivery confirmed", "shipment update"],
    scoreReduction: 20,
    description: "Legitimate service notification with specific details",
  },
];

export const SCAM_COMPOUND_PATTERNS = [
  {
    name: "Romance: Emotional Appeal + Financial Request",
    requiredGroups: [
      ["love", "miss you", "sweetheart", "darling", "honey", "my dear", "soulmate", "baby"],
      ["wire", "transfer", "send money", "gift card", "help me financially", "western union", "bitcoin", "wire transfer"],
    ],
    riskBonus: 20,
    multiplier: 2.5,
    description: "Emotional language combined with financial request — classic romance scam",
  },
  {
    name: "Romance: Military + Financial Request",
    requiredGroups: [
      ["military", "soldier", "overseas", "deployed", "oil rig", "engineer abroad"],
      ["wire", "transfer", "send money", "gift card", "help me financially", "western union"],
    ],
    riskBonus: 20,
    multiplier: 2.5,
    description: "Military romance scam pattern with financial request",
  },
  {
    name: "Romance: Relationship + Isolation + Financial",
    requiredGroups: [
      ["relationship", "dating", "love", "romance", "sweetheart"],
      ["keep private", "don't tell", "our secret", "just between us", "nobody needs to know"],
      ["money", "wire", "transfer", "gift card", "send", "help financially"],
    ],
    riskBonus: 25,
    multiplier: 2.5,
    description: "Relationship building with isolation tactics and financial request",
  },
  {
    name: "Grandparent: Family + Emergency + Financial + Secrecy",
    requiredGroups: [
      ["grandpa", "grandma", "grandson", "granddaughter", "grandchild", "nana", "papa"],
      ["emergency", "jail", "accident", "hospital", "bail", "arrested"],
      ["money", "wire", "transfer", "send", "gift card", "western union"],
    ],
    riskBonus: 25,
    multiplier: 2.5,
    description: "Classic grandparent scam with family emergency and financial request",
  },
  {
    name: "Grandparent: Urgency + Financial Request",
    requiredGroups: [
      ["grandchild", "grandson", "granddaughter", "grandma", "grandpa"],
      ["immediately", "urgent", "right now", "hurry", "quickly"],
      ["money", "wire", "send", "transfer", "bail"],
    ],
    riskBonus: 20,
    multiplier: 2.0,
    description: "Grandparent scam with urgency pressure",
  },
  {
    name: "Funeral: Financial Request + Urgency",
    requiredGroups: [
      ["funeral", "burial", "deceased", "cremation", "memorial", "remains", "death", "casket"],
      ["pay", "wire", "prepay", "immediately", "urgent", "transfer", "fee", "deposit", "payment"],
    ],
    riskBonus: 20,
    multiplier: 2.2,
    description: "Funeral scam combining death-related language with financial urgency",
  },
  {
    name: "Charity: Urgency + Payment Request",
    requiredGroups: [
      ["charity", "donation", "donate", "nonprofit", "help children", "save lives"],
      ["immediately", "urgent", "limited time", "today only", "act now", "matching donation"],
    ],
    riskBonus: 20,
    multiplier: 2.0,
    description: "Charity scam with urgency pressure",
  },
  {
    name: "Charity: Matching Donation Urgency",
    requiredGroups: [
      ["matching donation", "matching gift", "match your donation", "double your impact"],
      ["today", "limited time", "expires", "deadline", "act now", "immediately"],
    ],
    riskBonus: 15,
    multiplier: 1.8,
    description: "Fake matching donation creates false urgency",
  },
  {
    name: "Pet: Financial Request + Urgency",
    requiredGroups: [
      ["puppy", "kitten", "dog", "cat", "pet", "adoption", "rehome"],
      ["deposit", "shipping", "wire", "transfer", "fee", "payment"],
      ["urgent", "immediately", "quickly", "last one", "many inquiries", "leaving country"],
    ],
    riskBonus: 20,
    multiplier: 2.2,
    description: "Pet adoption scam with urgency and financial request",
  },
  {
    name: "Pet: Urgent Rehome",
    requiredGroups: [
      ["urgent rehome", "must find home", "leaving country", "free to good home"],
      ["deposit", "shipping fee", "transport fee", "wire", "transfer"],
    ],
    riskBonus: 18,
    multiplier: 2.2,
    description: "Fake urgent pet rehoming with financial request",
  },
];

export const KNOWN_COMPANIES = [
  { name: "amazon", domains: ["amazon.com", "amazon.co.uk", "amazon.ca"] },
  { name: "apple", domains: ["apple.com", "icloud.com"] },
  { name: "microsoft", domains: ["microsoft.com", "outlook.com", "live.com", "hotmail.com"] },
  { name: "google", domains: ["google.com", "gmail.com"] },
  { name: "paypal", domains: ["paypal.com"] },
  { name: "ebay", domains: ["ebay.com"] },
  { name: "walmart", domains: ["walmart.com"] },
  { name: "netflix", domains: ["netflix.com"] },
  { name: "facebook", domains: ["facebook.com", "meta.com"] },
  { name: "chase", domains: ["chase.com", "jpmorgan.com"] },
  { name: "bank of america", domains: ["bankofamerica.com"] },
  { name: "wells fargo", domains: ["wellsfargo.com"] },
  { name: "citibank", domains: ["citibank.com", "citi.com"] },
  { name: "usps", domains: ["usps.com"] },
  { name: "fedex", domains: ["fedex.com"] },
  { name: "ups", domains: ["ups.com"] },
  { name: "irs", domains: ["irs.gov"] },
  { name: "social security", domains: ["ssa.gov"] },
  { name: "target", domains: ["target.com"] },
  { name: "costco", domains: ["costco.com"] },
  { name: "best buy", domains: ["bestbuy.com"] },
  { name: "home depot", domains: ["homedepot.com"] },
  { name: "lowes", domains: ["lowes.com"] },
  { name: "capital one", domains: ["capitalone.com"] },
  { name: "american express", domains: ["americanexpress.com", "amex.com"] },
  { name: "discover", domains: ["discover.com"] },
  { name: "venmo", domains: ["venmo.com"] },
  { name: "zelle", domains: ["zellepay.com"] },
  { name: "coinbase", domains: ["coinbase.com"] },
  { name: "dhl", domains: ["dhl.com"] },
  { name: "cvs", domains: ["cvs.com"] },
  { name: "walgreens", domains: ["walgreens.com"] },
  { name: "td bank", domains: ["td.com", "tdbank.com"] },
  { name: "us bank", domains: ["usbank.com"] },
  { name: "pnc", domains: ["pnc.com"] },
  { name: "truist", domains: ["truist.com"] },
  { name: "verizon", domains: ["verizon.com"] },
  { name: "at&t", domains: ["att.com"] },
  { name: "comcast", domains: ["comcast.com", "xfinity.com"] },
  { name: "spectrum", domains: ["spectrum.com"] },
  { name: "t-mobile", domains: ["t-mobile.com"] },
  { name: "blue cross", domains: ["bcbs.com"] },
  { name: "aetna", domains: ["aetna.com"] },
  { name: "united healthcare", domains: ["uhc.com", "unitedhealthcare.com"] },
  { name: "cigna", domains: ["cigna.com"] },
  { name: "humana", domains: ["humana.com"] },
  { name: "kaiser permanente", domains: ["kaiserpermanente.org", "kp.org"] },
  { name: "spotify", domains: ["spotify.com"] },
  { name: "hulu", domains: ["hulu.com"] },
  { name: "disney+", domains: ["disneyplus.com", "disney.com"] },
  { name: "duke energy", domains: ["duke-energy.com"] },
  { name: "medicare", domains: ["medicare.gov", "cms.gov"] },
];

export const SUSPICIOUS_TLDS = [
  ".tk", ".ml", ".ga", ".cf", ".gq", ".xyz", ".top", ".buzz", ".club",
  ".work", ".click", ".link", ".info", ".win", ".bid", ".stream",
  ".loan", ".download", ".racing", ".date", ".review", ".party",
];

export const URL_SHORTENERS = [
  "bit.ly", "tinyurl.com", "t.co", "goo.gl", "is.gd", "buff.ly",
  "ow.ly", "adf.ly", "short.link", "rb.gy", "cutt.ly", "v.gd",
  "shorturl.at", "tiny.cc",
];
