export interface DailyQuote {
  text: string;
  author: string;
}

const DAILY_QUOTES: DailyQuote[] = [
  { text: "If you are going through hell, keep going.", author: "Winston Churchill" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { text: "Why not go out on a limb? That's where the fruit is.", author: "Mark Twain" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "Only I can change my life. No one can do it for me.", author: "Carol Burnett" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Life is about making an impact, not making an income.", author: "Kevin Kruse" },
  { text: "Happiness is the key to success.", author: "Albert Schweitzer" },
  { text: "Don't let a bad day make you think you have a bad life.", author: "Unknown" },
  { text: "Make the iron hot by striking.", author: "William Butler Yeats" },
  { text: "Turn the invisible into the visible.", author: "Tony Robbins" },
  { text: "Your thoughts shape the happiness of your life.", author: "Marcus Aurelius" },
  { text: "The second best time to plant a tree is now.", author: "Chinese Proverb" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "What lies within us is what truly matters.", author: "Ralph Waldo Emerson" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "You are never too old to set a new goal or dream.", author: "C.S. Lewis" },
  { text: "Keep your face toward the sunshine.", author: "Walt Whitman" },
  { text: "The purpose of life is a life of purpose.", author: "Robert Byrne" },
  { text: "It's not the goal — it's who you become reaching it.", author: "Zig Ziglar" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Hardships prepare ordinary people for greatness.", author: "C.S. Lewis" },
  { text: "The mind is everything. What you think, you become.", author: "Buddha" },
  { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Everything you want is on the other side of fear.", author: "George Addair" },
  { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "We become what we think about most of the time.", author: "Earl Nightingale" },
  { text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "Our only limit is our doubt.", author: "Franklin D. Roosevelt" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
  { text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
  { text: "We rise by lifting others.", author: "Robert Ingersoll" },
  { text: "Nothing is impossible. The word itself says 'I'm possible!'", author: "Audrey Hepburn" },
  { text: "Success is moving from failure to failure without losing heart.", author: "Winston Churchill" },
  { text: "Your present circumstances don't determine where you can go.", author: "Unknown" },
  { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "Perseverance is many short races, one after the other.", author: "Walter Elliot" },
  { text: "You don't have to be great to start — just start.", author: "Zig Ziglar" },
  { text: "One day or day one. You decide.", author: "Unknown" },
  { text: "When you have a dream, grab it and never let go.", author: "Carol Burnett" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "Kindness is a language the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "The best view comes after the hardest climb.", author: "Unknown" },
  { text: "Every day is a new beginning. Take a deep breath and start again.", author: "Unknown" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "The harder you work for something, the greater you'll feel.", author: "Unknown" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Zig Ziglar" },
  { text: "Be better than you were yesterday.", author: "Unknown" },
  { text: "Stay patient and trust your journey.", author: "Unknown" },
  { text: "Not all storms come to disrupt your life; some clear your path.", author: "Unknown" },
  { text: "A positive attitude can really make dreams come true.", author: "David Bailey" },
  { text: "Every moment is a fresh beginning.", author: "T.S. Eliot" },
  { text: "Your life is your story. Write well. Edit often.", author: "Susan Statham" },
  { text: "Wherever you go, go with all your heart.", author: "Confucius" },
  { text: "Stars can't shine without darkness.", author: "D.H. Sidebottom" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "It's not the hours you put in — it's what you put in.", author: "Unknown" },
  { text: "Challenges are what make life interesting.", author: "Joshua Marine" },
  { text: "The sun himself is weak when he first rises.", author: "Charles Dickens" },
  { text: "Life is short. Smile while you still have teeth.", author: "Mallory Hopkins" },
  { text: "Enjoy the little things. They may be the big things.", author: "Robert Brault" },
  { text: "A champion is defined not by their wins but by how they recover.", author: "Serena Williams" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "I have not failed. I've found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "Life isn't about finding yourself. It's about creating yourself.", author: "George Bernard Shaw" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "Goals matter less than who you become reaching them.", author: "Zig Ziglar" },
  { text: "The best is yet to come.", author: "Robert Browning" },
  { text: "No one is perfect — that's why pencils have erasers.", author: "Wolfgang Riebe" },
  { text: "You are braver than you believe, stronger than you seem.", author: "A.A. Milne" },
  { text: "Worry is a misuse of imagination.", author: "Dan Zadra" },
  { text: "Glory is not in never falling, but in rising every time.", author: "Confucius" },
  { text: "An obstacle is often a stepping stone.", author: "Prescott Bush" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Doing what you like is freedom. Liking what you do is happiness.", author: "Frank Tyger" },
  { text: "Kind words are short to speak, but their echoes are endless.", author: "Mother Teresa" },
  { text: "You always pass failure on the way to success.", author: "Mickey Rooney" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
  { text: "The only real mistake is the one from which we learn nothing.", author: "Henry Ford" },
  { text: "Hope is the thing with feathers that perches in the soul.", author: "Emily Dickinson" },
  { text: "First they ignore you, then they laugh, then you win.", author: "Mahatma Gandhi" },
  { text: "Once you choose hope, anything is possible.", author: "Christopher Reeve" },
  { text: "Where there is love, there is life.", author: "Mahatma Gandhi" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
  { text: "Spread love everywhere you go.", author: "Mother Teresa" },
  { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
  { text: "The only journey is the one within.", author: "Rainer Maria Rilke" },
  { text: "Peace begins with a smile.", author: "Mother Teresa" },
  { text: "Joy is not in things; it is in us.", author: "Richard Wagner" },
  { text: "To live is the rarest thing. Most people just exist.", author: "Oscar Wilde" },
  { text: "Let your smile change the world.", author: "Unknown" },
  { text: "The future belongs to those who believe in their dreams.", author: "Eleanor Roosevelt" },
  { text: "Live as if you were to die tomorrow. Learn as if forever.", author: "Mahatma Gandhi" },
  { text: "Dwell in possibility.", author: "Emily Dickinson" },
  { text: "You must be the change you wish to see.", author: "Mahatma Gandhi" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "In our darkest moments, we must focus to see the light.", author: "Aristotle" },
  { text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson" },
  { text: "Keep calm and carry on.", author: "British Government" },
  { text: "You have power over your mind — not outside events.", author: "Marcus Aurelius" },
  { text: "If not us, who? If not now, when?", author: "John F. Kennedy" },
  { text: "We do not remember days; we remember moments.", author: "Cesare Pavese" },
  { text: "I think, therefore I am.", author: "René Descartes" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "All we have to decide is what to do with the time given us.", author: "J.R.R. Tolkien" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Wisdom begins in wonder.", author: "Socrates" },
  { text: "Music expresses that which cannot be said.", author: "Victor Hugo" },
  { text: "Where there's a will, there's a way.", author: "English Proverb" },
  { text: "What does not kill me makes me stronger.", author: "Friedrich Nietzsche" },
  { text: "Know thyself.", author: "Socrates" },
  { text: "Time you enjoy wasting is not wasted time.", author: "Marthe Troly-Curtin" },
  { text: "This too shall pass.", author: "Persian Proverb" },
  { text: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { text: "Slow and steady wins the race.", author: "Aesop" },
  { text: "United we stand, divided we fall.", author: "Aesop" },
  { text: "Still waters run deep.", author: "English Proverb" },
  { text: "Actions speak louder than words.", author: "English Proverb" },
  { text: "With great power comes great responsibility.", author: "Voltaire" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "The journey is the reward.", author: "Steve Jobs" },
  { text: "Necessity is the mother of invention.", author: "Plato" },
  { text: "Two wrongs don't make a right.", author: "English Proverb" },
  { text: "Experience is the best teacher.", author: "Latin Proverb" },
  { text: "Less is more.", author: "Ludwig Mies van der Rohe" },
  { text: "Practice makes progress.", author: "Unknown" },
  { text: "Every cloud has a silver lining.", author: "John Milton" },
  { text: "The early bird catches the worm.", author: "English Proverb" },
  { text: "All's well that ends well.", author: "William Shakespeare" },
  { text: "Laughter is the best medicine.", author: "English Proverb" },
  { text: "You reap what you sow.", author: "Galatians 6:7" },
  { text: "Patience is a virtue.", author: "William Langland" },
  { text: "Home is where the heart is.", author: "Pliny the Elder" },
  { text: "Love conquers all.", author: "Virgil" },
  { text: "The truth will set you free.", author: "John 8:32" },
  { text: "No act of kindness, however small, is ever wasted.", author: "Aesop" },
  { text: "To thine own self be true.", author: "William Shakespeare" },
  { text: "That which does not bend, breaks.", author: "Japanese Proverb" },
  { text: "After rain comes sunshine.", author: "French Proverb" },
  { text: "A candle loses nothing by lighting another candle.", author: "James Keller" },
  { text: "The greatest wealth is health.", author: "Virgil" },
  { text: "When one door closes, another opens.", author: "Alexander Graham Bell" },
  { text: "Faith can move mountains.", author: "Matthew 17:20" },
  { text: "The best time to start was yesterday. The next best is now.", author: "Unknown" },
  { text: "Bloom where you are planted.", author: "Saint Francis de Sales" },
  { text: "Every expert was once a beginner.", author: "Helen Hayes" },
  { text: "When the caterpillar thought it was over, it became a butterfly.", author: "Chuang Tzu" },
  { text: "There is always light if only we're brave enough to see it.", author: "Amanda Gorman" },
  { text: "We grow not when things are easy, but when we face challenges.", author: "Unknown" },
  { text: "Your value doesn't decrease because someone can't see it.", author: "Unknown" },
  { text: "You are enough just as you are.", author: "Meghan Markle" },
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "Breathe. It's just a bad day, not a bad life.", author: "Unknown" },
  { text: "Good things take time.", author: "Unknown" },
  { text: "The comeback is always stronger than the setback.", author: "Unknown" },
  { text: "Gratitude turns what we have into enough.", author: "Melody Beattie" },
  { text: "Seek joy in the ordinary.", author: "Unknown" },
  { text: "You are never too old to reinvent yourself.", author: "Steve Harvey" },
  { text: "Age is just the number of years the world has enjoyed you.", author: "Unknown" },
  { text: "Growing old is mandatory. Growing up is optional.", author: "Walt Disney" },
  { text: "The afternoon knows what the morning never suspected.", author: "Robert Frost" },
  { text: "With age comes wisdom.", author: "Oscar Wilde" },
];

const DAILY_FACTS: DailyQuote[] = [
  { text: "Honey never spoils. Archaeologists have found 3,000 year old honey in Egyptian tombs that was still edible.", author: "Fact of the Day" },
  { text: "Octopuses have three hearts and blue blood.", author: "Fact of the Day" },
  { text: "A group of flamingos is called a flamboyance.", author: "Fact of the Day" },
  { text: "The human nose can detect over 1 trillion different scents.", author: "Fact of the Day" },
  { text: "Bananas are berries, but strawberries are not.", author: "Fact of the Day" },
  { text: "The Eiffel Tower can grow up to 6 inches taller during summer due to heat expansion.", author: "Fact of the Day" },
  { text: "A day on Venus is longer than a year on Venus.", author: "Fact of the Day" },
  { text: "The heart of a shrimp is located in its head.", author: "Fact of the Day" },
  { text: "Cows have best friends and get stressed when they are separated.", author: "Fact of the Day" },
  { text: "The inventor of the Pringles can is buried in one.", author: "Fact of the Day" },
  { text: "Alaska is the only state whose name is on one row of a keyboard.", author: "Fact of the Day" },
  { text: "Sea otters hold hands while they sleep so they do not drift apart.", author: "Fact of the Day" },
  { text: "There are more stars in the universe than grains of sand on all of Earth's beaches.", author: "Fact of the Day" },
  { text: "The longest hiccuping spree lasted 68 years.", author: "Fact of the Day" },
  { text: "A bolt of lightning is five times hotter than the surface of the sun.", author: "Fact of the Day" },
  { text: "The average person walks about 100,000 miles in their lifetime.", author: "Fact of the Day" },
  { text: "Dolphins sleep with one eye open.", author: "Fact of the Day" },
  { text: "A hummingbird weighs less than a nickel.", author: "Fact of the Day" },
  { text: "The Great Wall of China is not visible from space with the naked eye, but highways are.", author: "Fact of the Day" },
  { text: "Your body contains about 60,000 miles of blood vessels.", author: "Fact of the Day" },
  { text: "Elephants are the only animals that cannot jump.", author: "Fact of the Day" },
  { text: "Scotland's national animal is the unicorn.", author: "Fact of the Day" },
  { text: "There are more trees on Earth than stars in the Milky Way.", author: "Fact of the Day" },
  { text: "A group of owls is called a parliament.", author: "Fact of the Day" },
  { text: "The shortest war in history lasted 38 minutes, between Britain and Zanzibar.", author: "Fact of the Day" },
  { text: "Butterflies taste with their feet.", author: "Fact of the Day" },
  { text: "The average cloud weighs about 1.1 million pounds.", author: "Fact of the Day" },
  { text: "Venus is the only planet that spins clockwise.", author: "Fact of the Day" },
  { text: "A snail can sleep for three years.", author: "Fact of the Day" },
  { text: "The longest place name in the world has 85 letters and is a hill in New Zealand.", author: "Fact of the Day" },
  { text: "Wombat droppings are cube-shaped.", author: "Fact of the Day" },
  { text: "You cannot hum while holding your nose closed.", author: "Fact of the Day" },
  { text: "The total weight of all the ants on Earth is about the same as the weight of all the humans.", author: "Fact of the Day" },
  { text: "A jiffy is an actual unit of time equal to one hundredth of a second.", author: "Fact of the Day" },
  { text: "The moon has moonquakes, just like Earth has earthquakes.", author: "Fact of the Day" },
  { text: "Apples float in water because they are 25 percent air.", author: "Fact of the Day" },
  { text: "The first oranges were not orange in color. They were green.", author: "Fact of the Day" },
  { text: "Sloths can hold their breath longer than dolphins can.", author: "Fact of the Day" },
  { text: "There are more possible games of chess than atoms in the observable universe.", author: "Fact of the Day" },
  { text: "Goldfish have a memory span of at least three months, not three seconds.", author: "Fact of the Day" },
];

export function getDailyQuote(): DailyQuote {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor(
    (now.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)
  );
  const idx = dayOfYear - 1;
  if (idx % 2 === 0) {
    return DAILY_QUOTES[Math.floor(idx / 2) % DAILY_QUOTES.length];
  } else {
    return DAILY_FACTS[Math.floor(idx / 2) % DAILY_FACTS.length];
  }
}

export default DAILY_QUOTES;
