import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import userRouter from "./user.js";
import voiceRouter from "./voice.js";
import scamRouter from "./scam.js";
import familyRouter from "./family.js";
import alertsRouter from "./alerts.js";
import billingRouter from "./billing.js";
import supportRouter from "./support.js";
import conversationsRouter from "./conversations.js";
import hearingAidRouter from "./hearingAid.js";
import contactsRouter from "./contacts.js";
import emergencyRouter from "./emergency.js";
import adminRouter from "./admin.js";
import analyticsRouter from "./analytics.js";
import telecomRouter from "./telecom.js";
import insuranceRouter from "./insurance.js";
import facilitiesRouter from "./facilities.js";
import remindersRouter from "./reminders.js";
import healthAwarenessRouter from "./healthAwareness.js";
import schedulerRouter from "./scheduler.js";
import pushTokensRouter from "./push-tokens.js";

import { authLimiter, scamLimiter, voiceLimiter } from "../lib/rateLimit.js";

const router: IRouter = Router();

router.use("/", healthRouter);
router.use("/auth", authLimiter, authRouter);
router.use("/user", userRouter);
router.use("/voice", voiceLimiter, voiceRouter);
router.use("/scam", scamLimiter, scamRouter);
router.use("/family", familyRouter);
router.use("/alerts", alertsRouter);
router.use("/billing", billingRouter);
router.use("/support", supportRouter);
router.use("/conversations", conversationsRouter);
router.use("/hearing-aid", hearingAidRouter);
router.use("/contacts", contactsRouter);
router.use("/emergency", emergencyRouter);
router.use("/admin", adminRouter);
router.use("/analytics", analyticsRouter);
router.use("/telecom", telecomRouter);
router.use("/insurance", insuranceRouter);
router.use("/facilities", facilitiesRouter);
router.use("/reminders", remindersRouter);
router.use("/health-awareness", healthAwarenessRouter);
router.use("/scheduler", schedulerRouter);
router.use("/push-tokens", pushTokensRouter);

export default router;
